### PR TITLE
Landing page with getting started snippets

### PR DESCRIPTION
**Pull request by sunix**
Part of https://github.com/eclipse/jkube/issues/1425

Current Preview: https://jkube-website-quickstarts.surge.sh/jkube/
List of options:
  - [x] gradle-k8s,gradle-oc,mvn-k8s,mvn-oc ~in columns~
  - [x]  with big icons
  - [x] the lines to add to pom.xml/build.gradle
  - [x] link to documentation
  - [x] link to get started

### CODE REVIEW

**Comment by sunix** [comment]
usage of logo:
- [x] Eclipse Vertx - OK (Eclipse project)
- [x] JakartaEE - OK (Eclipse project)
- [x] Micronault: https://micronaut.io/brand-guidelines/micronaut-logos/ - JKube is not commercial and
         > Here are some ways you may use Micronaut trademarks:
         > § To describe the relationship between your product and/or service and the Micronaut
framework.`
- [x] Openliberty:   https://github.com/OpenLiberty/logos/blob/main/LICENSE.adoc
          > You are permitted to display and use the Open Liberty logos unmodified for the purpose of referencing the Open Liberty project or runtime in the following way:
          >  - Accurate statements about the compatibility of your product with Open Liberty
 - [ ] Quarkus
 - [ ] Spring boot
 - [ ] Gradle https://gradle.com/brand/ (no specific mention)
 - [ ] Maven
 - [ ]

**Review by rohanKanojia — APPROVED** [review]

**Comment by gbraad** [comment]
@manusa Can you have a look?

**Comment by manusa** [comment]
> @sunix Why is this still a draft?

This is on my plate now. Needs updating to change the styles + layout

> @manusa Can you have a look? 

This is one of my pending tasks. However, I had to prioritize other stuff during the past weeks.

**Comment by manusa** [comment]
I refactored most of the stuff to be compliant with Gatsby and React

A preview is available here https://jkube-website-quickstarts-iteration-2.surge.sh/jkube/

Changes include:
- Responsive design
- Use built-in React library for Tab management
- Tabs with icons
- Code interpolates version automatically
- Avoid usage of external resources

I opted to remove the diagram since I don't believe this will add to much value and it's hard to include with the current layout. My preference would be to reiterate over this in a future PR.

**Review by manusa — APPROVED** [review]

**Pull request merged**
